### PR TITLE
Mdandrad/program soa update

### PR DESCRIPTION
**Pull request by mdandrad**
Credentials Pull Request
https://its-pro.ucsd.edu/browse/EDX-452

*_I'm not sure if the changes to the models.py files are necessary with this pull request, feel free to remove_*

Make sure that the following steps are done before rebasing/merging

  - [x] Request a review if desired
  - [ ] Squash/Fixup your branch to one commit
  - Config/Dependency Changes (e.g. config files, scripts that are used for provisioning etc.)
    - [ ] Make sure you have updated [edx/configuration](https://github.com/edx/configuration) and [edx/devstack](https://github.com/edx/devstack) if necessary
    - [] Make sure the change builds successfully in a sandbox
  - UI Changes 
    - [ ] Consider other browsers (e.g. Firefox)
    - [ ] Check mobile view
    - [ ] Consider accessibility (e.g. Run aXe on the page)

### CODE REVIEW

**Comment by mdandrad** [comment]
@danialmalik 
CC @pjamason 

The error which was resolved when 'on_delete' attribute has been added

> Getting TypeError: __init__() missing 1 required positional argument: 'on_delete' when trying to add parent table after child table with entries

Django error? - https://docs.djangoproject.com/en/1.11/ref/models/fields/#foreignkey

**Comment by danialmalik** [comment]
@mdandrad when you've got some time, please mention the django version too here. 
You can use the following command (inside credentials shell) to get the django version.

```
make credentials-shell
python -m django --version
```

**Comment by mdandrad** [comment]
@danialmalik 
CC: @pjamason 
root@credentials:/edx/app/credentials/credentials# python -m django --version
1.11.15

**Comment by danialmalik** [comment]
@mdandrad @pjamason Just adding notes of our yesterday's discussion.
CC: @tasawernawaz , @imhassantariq 

This PR looks good but it will be better to dig deeper to understand the need and consequences of changing the models. We will work on that from our end and after making some discovery, we will be better able to decide if we want to have such database changes or not.
Also, without the migrations, these changes won't affect the database. Once we have decided to accept the changes, we will add those migrations too.

**Pull request merged**
